var citylist = {
	'Argentina': [
	    'Buenos Aires',
	],
	'Australia': [
	    'Adelaide, SA',
	    'Perth, WA',
	    'Sydney, NSW',
	],
	'Austria': [
	    'Baden',
	    'Bregenz',
	    'Dornbirn',
	    'Graz',
	    'Innsbruck',
	    'Klagenfurt',
	    'Krems',
	    'Linz',
	    'Salzburg',
	    'St. Pölten',
	    'Vienna',
	],
	'Belgium': [
	    'Antwerp',
	    'Brussels',
	    'Eupen',
	    'Geel',
	    'Genk',
	    'Ghent',
	    'Grand-Leez',
	    'Hornu',
	    'Leuven',
	    'Mechelen',
	    'Mons',
	    'Oostende',
	    'Otegem',
	],
	'Brazil': [
	    'São Paulo',
	],
	'Bulgaria': [
	    'Plovdiv',
	    'Sofia',
	],
	'Canada': [
	    'Montreal, QC',
	    'Toronto, ON',
	    'Vancouver, BC',
	],
	'Chile': [
	    'Santiago',
	],
	'China': [
	    'Beijing',
	    'Shanghai',
	],
	'Colombia': [
	    'Bogota',
	],
	'Czech Republic': [
	    'Olomouc',
	    'Prague',
	],
	'Denmark': [
	    'Aarhus',
	    'Askeby',
	    'Copenhagen',
	    'Esbjerg',
	    'Glostrup',
	    'Ishoj',
	    'Odense',
	    'Randers',
	    'Silkeborg',
	],
	'Ecuador': [
	    'Quito',
	],
	'Finland': [
	    'Espoo',
	    'Helsinki',
	    'Mikkeli',
	    'Pori',
	    'Salo',
	    'Tampere',
	    'Turku',
	],
	'France': [
	    'Albi',
	    'Alfortville',
	    'Bayeux',
	    'Besançon',
	    'Bordeaux',
	    'Brest',
	    'Chambord',
	    'Colmar',
	    'Colomiers',
	    'Delme',
	    'Dijon',
	    'Dunkerque',
	    'Eysines',
	    'Genevilliers',
	    'Grande-Synthe',
	    'Ivry sur Seine',
	    'Landerneau',
	    'Lannion',
	    'Lille',
	    'Louviers',
	    'Lyon',
	    'Malakoff',
	    'Marseille',
	    'Metz',
	    'Montpellier',
	    'Nancy',
	    'Nantes',
	    'Nîmes',
	    'Paris',
	    'Quimper',
	    'Rennes',
	    'Rouen',
	    'Saint-Etienne',
	    'Tours',
	],
	'Germany': [
	    'Aachen',
	    'Arnsberg',
	    'Arnstadt',
	    'Augsburg',
	    'Baden-Baden',
	    'Bad Homburg',
	    'Berlin',
	    'Bielefeld',
	    'Bochum',
	    'Bonn',
	    'Bremen',
	    'Bremerhaven',
	    'Brühl',
	    'Buchen',
	    'Büdelsdorf',
	    'Coburg',
	    'Coesfeld',
	    'Cologne',
	    'Darmstadt',
	    'Daun',
	    'Delmenhorst',
	    'Donaueschingen',
	    'Dortmund',
	    'Dresden',
	    'Dusseldorf',
	    'Erfurt',
	    'Erlangen',
	    'Eschweiler',
	    'Essen',
	    'Frankfurt/Main',
	    'Frankfurt/Oder',
	    'Freising',
	    'Gießen',
	    'Gladbeck',
	    'Göppingen',
	    'Göttingen',
	    'Grafenau',
	    'Hamburg',
	    'Hannover',
	    'Hattingen',
	    'Heidelberg',
	    'Heidenheim',
	    'Heilbronn',
	    'Herford',
	    'Hilden',
	    'Hildesheim',
	    'Husum',
	    'Ingolstadt',
	    'Iserlohn',
	    'Jena',
	    'Kaiserslautern',
	    'Karlsruhe',
	    'Kassel',
	    'Kiel',
	    'Knetzgau',
	    'Krefeld',
	    'Künzelsau',
	    'Langenhagen',
	    'Leipzig',
	    'Leonberg',
	    'Lübeck',
	    'Ludwigshafen',
	    'Mainz',
	    'Mannheim',
	    'Marl',
	    'Munich',
	    'Münster',
	    'Neunkirchen',
	    'Nordhorn',
	    'Nuremberg',
	    'Oberhausen',
	    'Oldenburg',
	    'Paderborn',
	    'Potsdam',
	    'Ravensburg',
	    'Regensburg',
	    'Riegel',
	    'Rotenburg',
	    'Saarbrücken',
	    'Schallstadt',
	    'Schwandorf',
	    'Sellin',
	    'Siegen',
	    'Sindelfingen',
	    'Stuttgart',
	    'Ulm',
	    'Wiesbaden',
	    'Wolfsburg',
	    'Wuppertal',
	    'Würzburg',
	],
	'Greece': [
	    'Athens',
	],
	'Hong Kong': [
	    'Hong Kong',
	],
	'Hungary': [
	    'Budapest',
	],
	'Iceland': [
	    'Reykjavik',
	],
	'India': [
	    'Bangalore',
	    'Mumbai',
	    'New Delhi',
	],
	'Israel': [
	    'Petach Tikva',
	    'Tel Aviv',
	],
	'Italy': [
	    'Bari',
	    'Bergamo',
	    'Bologna',
	    'Bolzano',
	    'Brescia',
	    'Catania, CT',
	    'Cremona',
	    'Florence',
	    'Milan',
	    'Monteriggioni, SI',
	    'Naples',
	    'Reggio Emilia',
	    'Rome',
	    'Rovereto',
	    'Turin',
	    'Venice',
	],
	'Japan': [
	    'Kitakyushu',
	    'Nagoya',
	    'Osaka',
	    'Shizuoka',
	    'Tokyo',
	],
	'Jordan': [
	    'Amman',
	],
	'Kuwait': [
	    'Kuwait City',
	],
	'Latvia': [
	    'Riga',
	],
	'Lebanon': [
	    'Beirut',
	],
	'Lithuania': [
	    'Vilnius',
	],
	'Luxembourg': [
	    'Luxembourg',
	],
	'Mexico': [
	    'Guadalajara',
	    'Mexico City',
	    'Zapopan',
	],
	'Netherlands': [
	    'Amsterdam',
	    'Eindhoven',
	    'Haarlem',
	    'Laren',
	    'Roermond',
	    'Rotterdam',
	    'The Hague',
	],
	'New Zealand': [
	    'Auckland',
	    'Dunedin',
	],
	'Nigeria': [
	    'Lagos',
	],
	'Norway': [
	    'Ålesund',
	    'Bergen',
	    'Moss',
	    'Nærbø',
	    'Oslo',
	    'Skien',
	    'Stavanger',
	    'Tønsberg',
	    'Tromsø',
	    'Trondheim',
	],
	'Peru': [
	    'Lima',
	],
	'Poland': [
	    'Kielce',
	    'Warsaw',
	],
	'Portugal': [
	    'Lisbon',
	],
	'Romania': [
	    'Bucharest',
	    'Cluj',
	],
	'Russia': [
	    'Moscow',
	],
	'Slovakia': [
	    'Bratislava',
	    'Nitra',
	],
	'Slovenia': [
	    'Ljubljana',
	    'Maribor',
	],
	'South Korea': [
	    'Busan',
	    'Cheonan-si',
	    'Daegu',
	    'Seoul',
	],
	'Spain': [
	    'Andratx',
	    'Barcelona',
	    'Bilbao',
	    'Burgos',
	    'Léon',
	    'Lleida',
	    'Madrid',
	    'Málaga',
	    'Santander',
	    'Sevilla',
	    'Valencia',
	    'Valladolid',
	    'Vigo',
	],
	'Sweden': [
	    'Borås',
	    'Gothenburg',
	    'Halmstad',
	    'Malmö',
	    'Skarhamn',
	    'Stockholm',
	    'Sundbyberg',
	    'Umeå',
	],
	'Switzerland': [
	    'Aarau',
	    'Basel',
	    'Bern',
	    'Chur',
	    'Davos',
	    'Geneva',
	    'Langenthal',
	    'Lausanne',
	    'Lens',
	    'Liestal',
	    'Lucerne',
	    'Oberwil',
	    'Rapperswil',
	    'Riehen',
	    'Thun',
	    'Zurich',
	],
	'Taiwan': [
	    'Taipei',
	],
	'Thailand': [
	    'Bangkok',
	],
	'Tunisia': [
	    'Sidi Bou Said',
	],
	'Turkey': [
	    'Istanbul',
	],
	'United Kingdom': [
	    'London',
	],
	'Uruguay': [
	    'Montevideo',
	],
	'USA': [
	    'Ann Arbor, MI',
	    'Aspen, CO',
	    'Atherton, CA',
	    'Atlanta, GA',
	    'Austin, TX',
	    'Baltimore, MD',
	    'Beverly Hills, CA',
	    'Birmingham, AL',
	    'Boston, MA',
	    'Boulder, CO',
	    'Buffalo, NY',
	    'Champaign, IL',
	    'Charlotte, NC',
	    'Charlottesville, VA',
	    'Chicago, IL',
	    'Claremont, CA',
	    'Culver City, CA',
	    'Dallas, TX',
	    'Daytona Beach, FL',
	    'Denver, CO',
	    'East Hampton, NY',
	    'Eugene, OR',
	    'Ferndale, MI',
	    'Greencastle, IN',
	    'Hartford, CT',
	    'Houston, TX',
	    'Irvine, CA',
	    'Jackson, WY',
	    'Jenkintown, PA',
	    'Kansas City, MO',
	    'Kensington, MD',
	    'Ketchum, ID',
	    'La Jolla, CA',
	    'Lincoln, MA',
	    'Los Angeles, CA',
	    'Miami Beach, FL',
	    'Miami, FL',
	    'Mill Valley, CA',
	    'Milwaukee, WI',
	    'Minneapolis, MN',
	    'Missoula, MT',
	    'New Orleans, LA',
	    'Newport Beach',
	    'New York City, NY',
	    'Oakland, CA',
	    'Philadelphia, PA',
	    'Pittsburg, PA',
	    'Portland, OR',
	    'Reno, NV',
	    'Richmond, VA',
	    'Ridgefield, CT',
	    'Sacramento, CA',
	    'Saint Louis, MO',
	    'San Antonio, TX',
	    'San Diego, CA',
	    'San Francisco, CA',
	    'San Jose, CA',
	    'Santa Fe, NM',
	    'Santa Monica, CA',
	    'Sarasota, FL',
	    'Savannah, GA',
	    'Seattle, WA',
	    'Tampa, FL',
	    'Tucson, AZ',
	    'Venice, CA',
	    'Washington, DC',
	    'Wichita, KS',
	    'Winter Park, FL',
	]
    };
